exchange:
  event.cron: 1 * * * * ?
  binance:
    api-key: ${BINANCE_API_KEY}
    secret: ${BINANCE_SECRET}

notification:
  pushover-properties:
    api-url: https://api.pushover.net/1/messages.json
    api-key: ${PUSHOVER_API_KEY}
    user-key: ${PUSHOVER_USER_KEY}