spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate

exchange:
  event.cron: 1 * * * * ?
  binance:
    api-key: test
    secret: test

notification:
  pushover-properties:
    api-url: https://api.pushover.net/1/messages.json
    api-key: ${PUSHOVER_API_KEY}
    user-key: ${PUSHOVER_USER_KEY}